name = "GenericCharacterTables"
uuid = "fdcc7804-6c20-4e83-8118-baad6b7d05b7"
authors = ["Andreas Leim <leim@rhrk.uni-kl.de>", "Martin Wagner <marwagne@rhrk.uni-kl.de>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
Oscar = "0.12, 0.13, 0.14"
julia = "1.6"
